include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**, test/**, example/**]
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true
  errors:
    avoid_print: true
    avoid_type_to_string: true

linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - await_only_futures
